# Generated by Django 5.2 on 2026-06-13 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Post Title (english)')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Post Title (arabic)')),
                ('content_en', models.TextField(verbose_name='Post Content (english)')),
                ('content_ar', models.TextField(verbose_name='Post Content (arabic)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Post Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
