# Generated by Django 5.2 on 2026-06-12 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Course Title (english)')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Course Title (arabic)')),
                ('description_en', models.TextField(verbose_name='Course Description (english)')),
                ('description_ar', models.TextField(verbose_name='Course Description (arabic)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='Price (SAR)')),
                ('image', models.ImageField(upload_to='course_images/', verbose_name='Course Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Video Title (english)')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Video Title (arabic)')),
                ('video_url', models.URLField(verbose_name='Video URL')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.course', verbose_name='Course')),
            ],
        ),
    ]
